### PR TITLE
feat(healthcheck): add healthcheck for all circuits

### PR DESCRIPTION
**Pull request by arthurtsang**
i've added new api to check the status of just one circuitbreaker and instead of just checking isOpen, i checked allowRequest as if the circuit is force opened, isOpen will return false.  also added a task to force open a circuit, this is useful for testing.  and also added a healthcheck.

### CODE REVIEW

**Comment by chrisgray** [comment]
Adding circuit breaker open/close behavior to healthchecks is a bit problematic I feel. Circuit breakers are very fluid especially under normal consistent traffic patterns. So taking an instantaneous snapshot can convey somewhat incorrect information (to be fair, breakerbox does per-second updating of this very same information).

The /healthcheck endpoint in dropwizard is very binary in it's health. The service is either healthy or unhealthy. Circuits however could only be used in certain endpoints and not necessarily all resource endpoints for the service. There is no partial health on a per-endpoint basis. In addition, circuits also often have fallback mechanisms hiding the fact that they may necessarily be open to requests (as by design). 

At the moment we do have a /tenacity/circuitbreakers endpoint that returns back the open circuit breakers at that instant.

As for the idea about being able to control a circuit to be open or not can be very useful indeed. We have thought about adding similar functionality as well. However, I feel there needs to be a bit more work on that one. Task might be too heavy weight instead of adding it as a resource under the adminConnector. The ability to forceOpen should also have the opposite to forceClose as well as the ability to reset so that the circuit is no longer in a forced state.

**Comment by arthurtsang** [comment]
the circuitbreaker healthcheck constructor allows user to put in the desired property key, so, we can only put those deem necessary to be running for the server to be considered healthy.  also, when a circuit is open, wouldn't that means it's unhealthy?  

breakerbox is great.  thanks for all the great work there (esp, no need to setup turbine & dashboard) but would healthcheck be easier for monitoring tools, like a simple script?

/tenacity/circuitbreakers does return it's status, however, it only check isOpen.  and if the circuit is force opened, isOpen will still return false.  adding allowRequest check would make sure it's really allowing traffic through.  (or we can add allowRequest to the response.)

the proposed implementation does allow to "forceClose" the circuit (actually, unset the forceOpen setting).  

however regarding to using task, i actually feel the opposite, even for /tenacity/circuitbreaks (and other resources.)  after all, those are not the main application logic (api) that I'm delivering.  I really would love to see them moved to admin port.  and tasks seems to be a good fit as forceOpen is really an action which is what task suppose to do.  

let me know if there's anything you think it's useful and how would you that to be implemented.  If there's nothing, I'll close the PR. 

Thanks,
Arthur Tsang

**Comment by chrisgray** [comment]
I went ahead and manually merged this into arthurtsang/circuitbreakers branch. I'll go ahead and get this into one of the next releases. I'll tweak somethings so that users can enable/disable healthchecks for their circuit breakers, adjust the circuitbreaker endpoint so that it leverages allowRequest, and add the ability to move these forceOpen/forceClose/reset options to the admin port.

**Comment by arthurtsang** [comment]
thanks

**Comment by chrisgray** [comment]
Just released this in 0.6.4 and 0.5.7 (dropwizard 0.7.x).

In a future release I'll add something to move all the resources from the application connector to the admin connector.

**Pull request closed without merging**
